import './styles/tailwind.css'
export { SuportumChat } from './templates/FloatingWidget'
export { ThemeProvider, useTheme } from './providers/ThemeProvider'
export { I18nProvider, useI18n } from './i18n'
export type { Locale } from './i18n'
